-- In database: cmca_audit
CREATE TABLE IF NOT EXISTS public.users (
  user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      TEXT    NOT NULL UNIQUE,
  password_hash TEXT    NOT NULL,
  user_type     TEXT    NOT NULL CHECK (user_type IN ('admin','general_user')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.projects (
  project_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_name TEXT    NOT NULL UNIQUE,
  created_by   BIGINT  NOT NULL REFERENCES public.users(user_id) ON DELETE RESTRICT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);