-- In database: cmca_audit
CREATE TABLE IF NOT EXISTS public.users (
  user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      TEXT    NOT NULL UNIQUE,
  password_hash TEXT    NOT NULL,
  user_type     TEXT    NOT NULL CHECK (user_type IN ('admin','general_user')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.projects (
  project_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_name TEXT    NOT NULL UNIQUE,
  created_by   BIGINT  NOT NULL REFERENCES public.users(user_id) ON DELETE RESTRICT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.pdfs (
  pdf_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title             TEXT,
  authors           TEXT,          
  affiliation       TEXT,
  doi               TEXT UNIQUE,
  instruments_json  JSONB,         
  num_pages         INTEGER,
  publish_date      TIMESTAMPTZ,   
  uploaded_by       BIGINT REFERENCES public.users(user_id)     ON DELETE SET NULL,
  project_id        BIGINT REFERENCES public.projects(project_id) ON DELETE SET NULL,
  upload_date       TIMESTAMPTZ NOT NULL DEFAULT now(),    
  cosine_similarity DOUBLE PRECISION,
  cmca_result       TEXT CHECK (cmca_result IN ('Yes','No'))
);

CREATE INDEX IF NOT EXISTS ix_pdfs_project_id  ON public.pdfs (project_id);
CREATE INDEX IF NOT EXISTS ix_pdfs_uploaded_by ON public.pdfs (uploaded_by);
CREATE INDEX IF NOT EXISTS ix_pdfs_doi         ON public.pdfs (doi);

ALTER TABLE public.pdfs
ADD COLUMN IF NOT EXISTS storage_path TEXT;